---
title: "Untitled"
output: html_document
date: '2022-06-10'
---
#Milk Spoilage working file

## Loading all the libraries.

```{r}
library(tidyverse)
library(ExtDist)
library(jmuOutlier)
library(truncnorm)
library(reshape2)
```

## Fucntions for growth and lag phases 
```{r}
#Function for growth and lag phase
new_growth_rate<-function(newTemp, oldMu,oldTemp = 6, T0 = -4.15){
  newMu<-((newTemp-T0)/(oldTemp-T0))* oldMu
  return (newMu)
}

#Calculation of the new lag time.
new_lag_time <- function (newTemp, oldLag, oldTemp = 6, T0 = -4.15) {
  numerator <- oldTemp -T0
  denom <- newTemp - T0
  newLag <- ( (numerator / denom)^2) * oldLag
  return(newLag)
}


#Automatic Time + Change function
look_for_st<-function(df = SpeciesDF,st, par_of_int){
  if (par_of_int == "lagt"){
    x<-df %>% 
      filter(ST == st) %>% 
      pull(lag_h)
  } else if (par_of_int == "mumax"){
    x<-df %>% 
      filter(ST == st) %>% 
      pull(mumax)
  } else if (par_of_int == "Nmax"){
    x<-df %>% 
      filter(ST == st) %>% 
      pull(Nmax)
  } else if (par_of_int == "GModel"){
    x<-df %>% 
      filter(ST == st) %>% 
      pull(GModel)
  }else {
    stop(paste0(par_of_int, " is not a valid parameter name. Must be one of lagt, mumax, Nmax"))
  }
  return(x)
}

Func_Growth_LagCon<-function(In_Lag_Consumed, Time_Temp_df,ST_Iter,Interval){
  #In_Lag_Consumed= Total lag time consumed
  #Time_Temp_df = dataframe with time and temperature conditions
  #ST_Iter = The ST that corresponds to this milk carton
  #Interval = time interval in the time_temp_df in hrs. 
  Total_Lag_Consumed<-In_Lag_Consumed
  Total_Growth  <- 0
  old_lag = look_for_st(st= ST_Iter, par_of_int = "lagt")
  old_mumax = look_for_st(st= ST_Iter, par_of_int = "mumax")
  for (i in 1:nrow(Time_Temp_df)){
    if (Total_Lag_Consumed <1 && old_lag!=0){
      Lag_t_interval<-new_lag_time(newTemp = Time_Temp_df$means[i], oldLag = old_lag)
      Lag_Consumed<-Interval/Lag_t_interval
      Total_Lag_Consumed<-Total_Lag_Consumed+Lag_Consumed
      Growth = 0
    } else if (Total_Lag_Consumed>=1 | old_lag == 0){
      Growth = ((new_growth_rate(newTemp = Time_Temp_df$means[i], oldMu = old_mumax))/2.303)*0.684 #Converted log10 from log ln
      Total_Growth = Total_Growth + (Growth*Interval)
    }
  }
  return(c(Total_Growth,Total_Lag_Consumed))
}

Time_Temp_Creation<-function(Total_Time, Interval, Initial_Temperature, Final_Temperature){
  Time_Temp_df<-data.frame("min"= seq(0,Total_Time,by = Interval),
                         "means"  = seq(Initial_Temperature,Final_Temperature, by = ((Final_Temperature - Initial_Temperature)/(length(seq(0,Total_Time,by = Interval)) - 1) )))
}

```

## Loading the species df
```{r}
SpeciesDF<-read_csv("SpeciesData.csv")
Prevs<-c(8.93,0.65,1.53,0.87,8.93,0.22,1.31,1.31,0.22,0.22,2.18,2.18)
Prevs<-Prevs/sum(Prevs)
SpeciesDF$Prev<-Prevs

```

## Time and Temperature profile data frame


## Buchanan Spoilage
```{r}


Spoilage_Function<-function(Milkdf,Time_Temp_df){
  for(i in 1:nrow(Milkdf)){
  In_Lag_Consumed<-Milkdf$LagCon[i]
  ST_Iter<-Milkdf$Species[i]
  Pop_Max<-look_for_st(st= ST_Iter,par_of_int = "Nmax")
  #Creating Time Temp Df

  #Temperature_Static<- rlaplace(1,m=4.06,s=2.31)
  #while (Temperature_Static > 15 | Temperature_Static < -1) {
   # Temperature_Static<- rlaplace(1,m=4.06,s=2.31)
  #}
  #Time_Temp_df<-Time_Temp_Creation(Total_Time = 24*14, Interval = 0.5, Initial_Temperature = Temperature_Static, Final_Temperature = `#Temperature_Static)
  
  Interval <- Time_Temp_df$min[2]/60
  
  Output_Milk<-Func_Growth_LagCon(In_Lag_Consumed = In_Lag_Consumed ,Time_Temp_df = Time_Temp_df,ST_Iter = ST_Iter,Interval = Interval)
  
  Milkdf$LagCon[i]<-Output_Milk[2]
  Milkdf$SpoilageCon[i]<-Output_Milk[1]+Milkdf$SpoilageCon[i]
  if(Milkdf$SpoilageCon[i]>Pop_Max){
    Milkdf$SpoilageCon[i]<-Pop_Max
  }
}
return(Milkdf)
}

Spoilage_Function_Apply<-function(Milkdf,Time_Temp_df){
  In_Lag_Consumed<-Milkdf[3] #Lag Con
  ST_Iter<-Milkdf[4] #Species
  Pop_Max<-look_for_st(st= ST_Iter,par_of_int = "Nmax")
  
  Interval <- 1/60
  
  Output_Milk<-Func_Growth_LagCon(In_Lag_Consumed = In_Lag_Consumed ,Time_Temp_df = Time_Temp_df,ST_Iter = ST_Iter,Interval = Interval)
  
  Milkdf[3]<-Output_Milk[2]
  Milkdf[2]<-Output_Milk[1]+Milkdf[2]
  if(Milkdf[2]>Pop_Max){
    Milkdf[2]<-Pop_Max
  }
  return(Milkdf)
}

```

#Small Validation Scenario
```{r}
Temperature_Static<- rlaplace(1,m=4.06,s=2.31)
while (Temperature_Static > 15 | Temperature_Static < -1) {
  Temperature_Static<- rlaplace(1,m=4.06,s=2.31)
}
Time_Temp_df<-data.frame("min"= seq(1,10080))
Time_Temp_df$means = 4.06


Milkdf<-data.frame("MilkID" = seq(0,100),"SpoilageCon" =NA, "LagCon" = 0, "Species" = NA)
Milkdf$Species<-sample(SpeciesDF$ST,size = length(Milkdf$Species), prob = SpeciesDF$Prev, replace = T)
Milkdf$SpoilageCon<-rtruncnorm(n = length(Milkdf$SpoilageCon),b = 3, mean =0.3817872, sd=1.108859)
Milkdf$SpoilageConIn<-Milkdf$SpoilageCon

mean(Milkdf$SpoilageConIn)

for (i in 1:N_Days){
  Milkdf<-Spoilage_Function(Milkdf,Time_Temp_df)
}

mean(Milkdf$SpoilageCon)


```




#Experiment Worse case scenario with Tray with Ice
```{r}
Milkdf<-data.frame("MilkID" = seq(0,100),"SpoilageCon" =NA, "LagCon" = 0, "Species" = NA)
Milkdf$Species<-sample(SpeciesDF$ST,size = length(Milkdf$Species), prob = SpeciesDF$Prev, replace = T)
Milkdf$SpoilageCon<-rtruncnorm(n = length(Milkdf$SpoilageCon),b = 3, mean =0.3817872, sd=1.108859)
Milkdf$SpoilageConIn<-Milkdf$SpoilageCon

mean(Milkdf$SpoilageCon)
  
N_Days = 5

for (i in 1:N_Days){
 #Service 1:
Milkdf<-Spoilage_Function(Milkdf,TI_L_FT_L1)
#Break 1:
Milkdf<-Spoilage_Function(Milkdf,TI_L_FT_B1)
#Lunch 2:
Milkdf<-Spoilage_Function(Milkdf,TI_L_FT_L2) 
#Overnight
Milkdf<-Spoilage_Function(Milkdf,OvernightSto_C)
print(paste("Day", i))
}

Milkdf$Change  = Milkdf$SpoilageCon-Milkdf$SpoilageConIn

mean(Milkdf$Change)

Milkdf_Melted<-melt(Milkdf, id.vars = c("MilkID", "LagCon", "Species"))

Milkdf_Melted %>% 
  ggplot(aes(x =value, group= variable, fill= variable))+
  geom_density( alpha = 0.5)

Milkdf_Melted %>% 
  ggplot(aes(y =value , group= variable, x= variable))+
  geom_boxplot()+
  labs(y = "log CFU/mL")+
  geom_hline(yintercept = 4.30, color = "red", size = 1)

sum(Milkdf$SpoilageCon>4.30)/(100)

```

##Experiment worse case scenario room temp B: 

```{r}
Milkdf<-data.frame("MilkID" = seq(0,100),"SpoilageCon" =NA, "LagCon" = 0, "Species" = NA)
Milkdf$Species<-sample(SpeciesDF$ST,size = length(Milkdf$Species), prob = SpeciesDF$Prev, replace = T)
Milkdf$SpoilageCon<-rtruncnorm(n = length(Milkdf$SpoilageCon),b = 3, mean =0.3817872, sd=1.108859)
Milkdf$SpoilageConIn<-Milkdf$SpoilageCon


N_Days = 5


for (i in 1:N_Days){
#Service 1:
Milkdf<-Spoilage_Function(Milkdf,RTB_L_NT_L1)
#Break 1:
Milkdf<-Spoilage_Function(Milkdf,RTB_L_NT_B1)
#Lunch 2:
Milkdf<-Spoilage_Function(Milkdf,RTB_L_NT_B1)
#ON Storage
Milkdf<-Spoilage_Function(Milkdf,OvernightSto_C)
print(paste("Day", i))
}

library(reshape2)

Milkdf_Melted<-melt(Milkdf, id.vars = c("MilkID", "LagCon", "Species"))

Milkdf_Melted %>% 
  ggplot(aes(x =value, group= variable, fill= variable))+
  geom_density( alpha = 0.5)

Milkdf_Melted %>% 
  ggplot(aes(y =value , group= variable, x= variable))+
  geom_boxplot()+
  labs(y = "log CFU/mL")+
  geom_hline(yintercept = 4.30, color = "red", size = 1)

sum(Milkdf$SpoilageCon>4.30)/(100)
  
```

## Worse case scenario Ref Tray
```{r}
Milkdf<-data.frame("MilkID" = seq(0,100),"SpoilageCon" =NA, "LagCon" = 0, "Species" = NA)
Milkdf$Species<-sample(SpeciesDF$ST,size = length(Milkdf$Species), prob = SpeciesDF$Prev, replace = T)
Milkdf$SpoilageCon<-rtruncnorm(n = length(Milkdf$SpoilageCon),b = 3, mean =0.3817872, sd=1.108859)
Milkdf$SpoilageConIn<-Milkdf$SpoilageCon


N_Days = 5


for (i in 1:N_Days){
#Service 1:
Milkdf<-Spoilage_Function(Milkdf,RefT_L_NT_L1)
#Break 1:
Milkdf<-Spoilage_Function(Milkdf,RefT_L_NT_B1)
#Lunch 2:
Milkdf<-Spoilage_Function(Milkdf,RefT_L_NT_B1)
#ON Storage
Milkdf<-Spoilage_Function(Milkdf,OvernightSto_C)
print(paste("Day", i))
}

library(reshape2)

Milkdf_Melted<-melt(Milkdf, id.vars = c("MilkID", "LagCon", "Species"))

Milkdf_Melted %>% 
  ggplot(aes(x =value, group= variable, fill= variable))+
  geom_density( alpha = 0.5)

Milkdf_Melted %>% 
  ggplot(aes(y =value , group= variable, x= variable))+
  geom_boxplot()+
  labs(y = "log CFU/mL")+
  geom_hline(yintercept = 4.30, color = "red", size = 1)

```

################################################################## 

```{r}
Milkdf<-data.frame("MilkID" = seq(0,100),"SpoilageCon" =NA, "LagCon" = 0, "Species" = NA)
Milkdf$Species<-sample(SpeciesDF$ST,size = length(Milkdf$Species), prob = SpeciesDF$Prev, replace = T)
Milkdf$SpoilageCon<-rtruncnorm(n = length(Milkdf$SpoilageCon),b = 3, mean =0.3817872, sd=1.108859)
Milkdf$SpoilageConIn<-Milkdf$SpoilageCon


N_Days = 1


for (i in 1:N_Days){
  #Service 1:
  Milkdf<-t(as.data.frame(apply(Milkdf,1,Spoilage_Function_Apply, Time_Temp_df = RTB_L_NT_L1)))
  #Break 1:
  Milkdf<-t(as.data.frame(apply(Milkdf,1,Spoilage_Function_Apply, Time_Temp_df = RTB_L_NT_B1)))
  #Lunch 2:
  Milkdf<-t(as.data.frame(apply(Milkdf,1,Spoilage_Function_Apply, Time_Temp_df = RTB_L_NT_L2)))
  #ON Storage
  Milkdf<-  Milkdf<-t(as.data.frame(apply(Milkdf,1,Spoilage_Function_Apply, Time_Temp_df = OvernightSto_C)))
  print(paste("Day", i))
}

library(reshape2)

Milkdf_Melted<-melt(Milkdf, id.vars = c("MilkID", "LagCon", "Species"))

Milkdf_Melted %>% 
  ggplot(aes(x =value, group= variable, fill= Var2))+
  geom_density( alpha = 0.5)

Milkdf_Melted %>% 
  ggplot(aes(y =value , group= Var2, x= Var2))+
  geom_boxplot()+
  labs(y = "log CFU/mL")+
  geom_hline(yintercept = 4.30, color = "red", size = 1)

```


