---
title: "Untitled"
output: html_document
date: '2022-07-25'
---

#Milk Temperature Curves Validation

loading the Heat Transfer Coefficients
```{r}
#Standard Inputs
rho <-1.033 #kg/L
C <- 4.2 #kj/KgC°
V <- 0.236 #L
A <- 0.004275 #m2


get_h<-function(Neg_slope, rho = 1.033, C = 4.2 , V = 0.236, A = 0.004275){
  neg_h =  ((Neg_slope*rho*C*V)/A)
  return(- neg_h)
} 

#Negative Slopes
Neg_Slope_RTB<-(-0.0124) #Room Temperature
Neg_Slope_Ref<-(-0.0141) #Refrigeration
Neg_Slope_RT<-(-0.0088) #Refrigerated Tray
Neg_Slope_TIC<-(-0.0057) #Tray with Ice 
Neg_Slope_TIP<-(-0.0072) #Tray with Ice Packs
Neg_Slope_CI<-(-0.0019) #Cooler with Ice

#Getting the Heat Transfer Coefficients for each Temp
h_RTB = get_h(Neg_slope = Neg_Slope_RTB)
h_ref = get_h(Neg_slope = Neg_Slope_Ref)
h_RT = get_h(Neg_slope = Neg_Slope_RT)
h_TIC = get_h(Neg_slope = Neg_Slope_TIC)
h_TIP = get_h(Neg_slope = Neg_Slope_TIP)
h_CI = get_h(Neg_slope = Neg_Slope_CI)


#Function to get temperature as a constant time and temperature
get_temp<-function(h, To, Tinf, time,  A =0.004275,rho =1.033, C= 4.2, V = 0.236 ){
  #Time in minutes
  #Tinf = External Temp
  #To = Initial temperature of the milk
  # h = convection trans coefficient for that condition
  return (exp(-(h*A/rho*C*V)*(time))*(To-Tinf)+Tinf)
}
```

##Function to create time and temp profiles vector
```{r}
#Constant outside temperature
predict_temp<-function(Initial_Temp, Room_temp, Total_min, h_condition){
  #Returns a vector of temperatures
  Total_Time_min = Total_min
  Temp_Initial = Initial_Temp
  T_inf = Room_temp
  Temp_V<-c()
  for (i in 1:Total_Time_min){
    if (i == 1){
      New_Temp = Temp_Initial
    }else if (i == 2){
      New_Temp = get_temp(h = h_condition, To = Temp_Initial, Tinf =  T_inf, time = 1)
    }else{
      New_Temp = get_temp(h = h_condition, To = New_Temp, Tinf =  T_inf, time = 1)
    }
    Temp_V<-c(Temp_V, New_Temp)
  }
  return (Temp_V)
}


predict_temp(Initial_Temp = 4.5,Room_temp = 22, Total_min = 42, h_condition = h_RTB)


#Predicting the temperature from a complete time and temperature profile.
predict_temp_fromProf<-function(Time_Temp_Prof, Initial_Temp,h_condition){
  Time_Temp_Profile<-Time_Temp_Prof
  Temp_Initial = Initial_Temp
  Temp_V<-c()
  for (i in 1:length(Time_Temp_Profile)){
    T_inf<-Time_Temp_Profile[i]
    if (i == 1){
      New_Temp = Temp_Initial
    }else if (i == 2){
      New_Temp = get_temp(h = h_condition, To = Temp_Initial, Tinf =  T_inf, time = 1)
    }else{
      New_Temp = get_temp(h = h_condition, To = New_Temp, Tinf =  T_inf, time = 1)
    }
    Temp_V<-c(Temp_V, New_Temp)
  }
  return(Temp_V)
}


Time_Temp_Creation_Var<-function(Total_Time, Interval, Mean_Temperature, SD_Temperature){
  Time_Temp_df<-data.frame("min"= seq(0,Total_Time,by = Interval),
                         "tempM"= rnorm(n =Total_Time+1, mean = Mean_Temperature, sd= SD_Temperature))
  return (Time_Temp_df)
}

```


```{r}
calc_rmse=function(actual, predicted) {
  sqrt(mean((actual - predicted) ^ 2))
}

Condition_Data<-read.csv("Bevier_Trial_Temps_External.csv")
Condition_Data_InternalMilk<-read.csv("Bevier_Trial_Temps_Internal.csv")

Predicted_RTB<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Ambient.Temperature, Initial_Temp = Condition_Data_InternalMilk$Ambient.Temperature[1], h_condition = h_RTB)

Predicted_RT<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Refrigerated.Tray, Initial_Temp = Condition_Data_InternalMilk$Refrigerated.Tray[1], h_condition = h_RT)

Predicted_TI<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Tray.with.Ice, Initial_Temp = Condition_Data_InternalMilk$Tray.with.Ice[1], h_condition = h_TIC)

Predicted_TIP<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Tray.with.Ice.Packs, Initial_Temp = Condition_Data_InternalMilk$Tray.with.Ice.Packs[1], h_condition = h_TIP)

Predicted_CI<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Cooler.with.Ice, Initial_Temp = Condition_Data_InternalMilk$Cooler.with.Ice[1], h_condition = h_CI)


calc_rmse(actual = Condition_Data_InternalMilk$Ambient.Temperature, predicted = Predicted_RTB[1:50])
calc_rmse(actual = Condition_Data_InternalMilk$Refrigerated.Tray, predicted = Predicted_RT[1:50])
calc_rmse(actual = Condition_Data_InternalMilk$Tray.with.Ice, predicted = Predicted_TI[1:50])
calc_rmse(actual = Condition_Data_InternalMilk$Tray.with.Ice.Packs, predicted = Predicted_TIP[1:50])
calc_rmse(actual = Condition_Data_InternalMilk$Cooler.with.Ice, predicted = Predicted_CI[1:50])


PredictionDf<-data.frame("Time" = c(1:51),
                         "Ambient.Temperature" = Predicted_RTB,
                         "Cooler.with.Ice" = Predicted_CI,
                         "Tray.with.Ice"= Predicted_TI,
                         "Tray.with.Ice.Packs"= Predicted_TIP,
                         "Refrigerated.Tray" = Predicted_RT)

library(reshape2)
library(ggplot2)
Internal_DF<-reshape2::melt(Condition_Data_InternalMilk, id.vars = "Time")
Internal_DF$type<-"Observed"

Predicted_DF<-reshape2::melt(PredictionDf, id.vars = "Time")
Predicted_DF$type<-"Predicted"

Predicted_vs_Observed<-rbind(Internal_DF,Predicted_DF)


#RMSE and Text
dat_text <- data.frame(
label = c("RMSE: 0.72", "RMSE: 0.24", "RMSE:0.50", "RMSE: 0.32", "RMSE: 0.12"),
 variable   = c("Ambient.Temperature","Cooler.with.Ice","Tray.with.Ice","Tray.with.Ice.Packs","Refrigerated.Tray"),
  x     = c(30, 30, 30,30,30),
  y     = c(4, 2, 3,3,4)
)

dat_text_h <- data.frame(
label = c("h: 2.96", "h: 0.455", "h: 1.36", "h: 1.72", "h: 2.10"),
 variable   = c("Ambient.Temperature","Cooler.with.Ice","Tray.with.Ice","Tray.with.Ice.Packs","Refrigerated.Tray"),
  x     = c(30, 30, 30,30,30),
  y     = c(3, 1.85, 2.5,2.4,3.4)
)


Labels<-c("Ambient.Temperature"="Ambient Temperature", 
          "Cooler.with.Ice"="Cooler with Ice", 
          "Tray.with.Ice"="Tray with Ice", 
          "Tray.with.Ice.Packs"="Tray with Ice Packs", 
          "Refrigerated.Tray"="Refrigerated Tray")

ggplot(Predicted_vs_Observed, aes(x = Time))+
  #geom_point(aes(y = value, color = type))+
  geom_line(aes(y = value, color = type), size=1)+
  facet_wrap(~variable, scales = "free_y", labeller = labeller(variable= Labels))+
  theme_bw()+
  labs(y = "Temperature (°C)", x = "Time (min)", color = "Observer vs Predicted")+
  geom_text(data    = dat_text,
  mapping = aes(x = x, y = y, label = label), size =3.5)+
    geom_text(data    = dat_text_h,
  mapping = aes(x = x, y = y, label = label), size =3.5)

```




##For half time in condition

```{r}
Condition_Data<-read.csv("Bevier_Trial_Temps_External_30min.csv")
Condition_Data_InternalMilk<-read.csv("Bevier_Trial_Temps_Internal_30min.csv")

Predicted_RTB<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Ambient.Temperature, Initial_Temp = Condition_Data_InternalMilk$Ambient.Temperature[1], h_condition = h_RTB)

Predicted_RT<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Refrigerated.Tray, Initial_Temp = Condition_Data_InternalMilk$Refrigerated.Tray[1], h_condition = h_RT)

Predicted_TI<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Tray.with.Ice, Initial_Temp = Condition_Data_InternalMilk$Tray.with.Ice[1], h_condition = h_TIC)

Predicted_TIP<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Tray.with.Ice.Packs, Initial_Temp = Condition_Data_InternalMilk$Tray.with.Ice.Packs[1], h_condition = h_TIP)

Predicted_CI<-predict_temp_fromProf(Time_Temp_Prof =Condition_Data$Cooler.with.Ice, Initial_Temp = Condition_Data_InternalMilk$Cooler.with.Ice[1], h_condition = h_CI)


calc_rmse(actual = Condition_Data_InternalMilk$Ambient.Temperature, predicted = Predicted_RTB)
calc_rmse(actual = Condition_Data_InternalMilk$Refrigerated.Tray, predicted = Predicted_RT)
calc_rmse(actual = Condition_Data_InternalMilk$Tray.with.Ice, predicted = Predicted_TI)
calc_rmse(actual = Condition_Data_InternalMilk$Tray.with.Ice.Packs, predicted = Predicted_TIP)
calc_rmse(actual = Condition_Data_InternalMilk$Cooler.with.Ice, predicted = Predicted_CI)


PredictionDf<-data.frame("Time" = c(1:30),
                         "Ambient.Temperature" = Predicted_RTB,
                         "Cooler.with.Ice" = Predicted_CI,
                         "Tray.with.Ice"= Predicted_TI,
                         "Tray.with.Ice.Packs"= Predicted_TIP,
                         "Refrigerated.Tray" = Predicted_RT)

library(reshape2)
library(ggplot2)
Internal_DF<-reshape2::melt(Condition_Data_InternalMilk, id.vars = "Time")
Internal_DF$type<-"Observed"

Predicted_DF<-reshape2::melt(PredictionDf, id.vars = "Time")
Predicted_DF$type<-"Predicted"

Predicted_vs_Observed<-rbind(Internal_DF,Predicted_DF)

Labels<-c("Ambient.Temperature"="Ambient Temperature", 
          "Cooler.with.Ice"="Cooler with Ice", 
          "Tray.with.Ice"="Tray with Ice", 
          "Tray.with.Ice.Packs"="Tray with Ice Packs", 
          "Refrigerated.Tray"="Refrigerated Tray")

ggplot(Predicted_vs_Observed, aes(x = Time))+
  #geom_point(aes(y = value, color = type))+
  geom_line(aes(y = value, color = type), size=1)+
  facet_wrap(~variable, scales = "free_y", labeller = labeller(variable= Labels))+
  theme_bw()+
  labs(y = "Temperature (°C)", x = "Time (min)", color = "Observer vs Predicted")

```










```{r}
Actual_Temps<-read.csv("Validation Milk Temps.csv")

Simulated_RT<-Time_Temp_Creation_Var(Total_Time = 125, Interval = 1, Mean_Temperature = 22.1, SD_Temperature = 0.77)
Simulated_Ref<-Time_Temp_Creation_Var(Total_Time = 300, Interval = 1, Mean_Temperature = 3.71, SD_Temperature = 1.04)


Simulated_M_1<-predict_temp_fromProf(Time_Temp_Prof = Simulated_RT$tempM, Initial_Temp = 4.2, h_condition = h_RTB)
Simulated_M_2<-predict_temp_fromProf(Time_Temp_Prof = Simulated_Ref$tempM, Initial_Temp = 17.98, h_condition = h_ref)

Full_df<-data.frame("Simulated Temps" = c(Simulated_M_1,Simulated_M_2),
                    "Actual Temps" = Actual_Temps,
                    "Time" = c(1:427))

Full_df_melted<-melt(Full_df, id.vars = "Time")

ggplot(aes(x = Time, y= value, color= variable ), data = Full_df_melted)+
  geom_point()

predict_temp(Initial_Temp = 4.5,Room_temp = 25, Total_min = 600, h_condition = h_RTB)
plot(predict_temp(Initial_Temp = 18,Room_temp = 8, Total_min = 600, h_condition = h_ref))


```


